import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Ubuntu, Dancing_Script, Poppins } from "next/font/google";
import Boxes from "@/components/Boxes/Boxes";

import Pen from '../public/assets/pen.json';
import Computer from '../public/assets/computer.json';
import Clock from '../public/assets/clock.json';
import Money from '../public/assets/money.json';
import Check from '../public/assets/check.json';
import Person from '../public/assets/person.json';

import ServiceCard from "@/components/ServiceCard/ServiceCard";
import FeatureCard from "@/components/FeatureCard/FeatureCard";
import ProjectCard from "@/components/ProjectCard/ProjectCard";
import { useEffect, useRef, useState } from "react";
import ReviewCard from "@/components/ReviewCard/ReviewCard";
import FaqCard from "@/components/FaqCard/FaqCard";


// Font imports
const ubuntu = Ubuntu({ weight: ['500', '700'], subsets: ['latin'] });
const dancing = Dancing_Script({ weight: ['500', '700'], subsets: ['latin'] });
const poppins = Poppins({ weight: ['500', '700'], subsets: ['latin'] });

export default function Home() {

  const ref = useRef();

  const [visibilityPercentage, setVisibilityPercentage] = useState(0);
  const [containerIsVisible, setContainerIsVisible] = useState(false);
  const [count, setCount] = useState(0);

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        // Calculate the percentage of the element visible in the viewport
        const visiblePercentage = entry.intersectionRatio * 100;
        setVisibilityPercentage(visiblePercentage.toFixed(2)); // Keep it to 2 decimal places
      },
      {
        threshold: Array.from(Array(101).keys(), i => i / 100), // Create thresholds from 0% to 100%
      }
    );

    if (ref.current) {
      observer.observe(ref.current);
    }

    return () => {
      if (ref.current) {
        observer.unobserve(ref.current);
      }
    };
  }, [visibilityPercentage]);

  useEffect(() => {
    if (count <= 0 && visibilityPercentage >= 50) {
      setContainerIsVisible(prev => !prev);
      setCount(prev => prev + 1);
    }
  }, [visibilityPercentage]);

  return (
    <div className={styles.parent}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Background squares layer */}
      <div className={styles.backgroundWrapper}>

        <main className={styles.main}>
          <div className={styles.Banner}>
            <span className={`${dancing.className} ${styles.bannerTextOne}`}>Welcome to Hawkflit</span>
            <h2 className={`${ubuntu.className} ${styles.bannerTextTwo}`}>
              Your partner studio for Web Development, App Development, UI/UX, SEO, and Analytics.
            </h2>
            <span className={`${poppins.className} ${styles.bannerTextThree}`}>
              Designing stunning products, visuals, brands, and websites
            </span>
            <div className={`${styles.bookContainer} ${poppins.className}`}>
              Book a call
            </div>
          </div>
        </main>

        <Boxes />
      </div>

      {/* Marquee section */}
      <div className={`${styles.marqueeContainer} ${poppins.className}`}>
        <img src="/marquee/img-bridge.svg" alt="image bridge" className={styles.imgBridge} />
        <div className={styles.marquee}>
          <img src="/marquee/aws.svg" alt="" />
          <img src="/marquee/figma.svg" alt="" />
          <img src="/marquee/firebase.svg" alt="" />
          <img src="/marquee/github.svg" alt="" />
          <img src="/marquee/jira.svg" alt="" />
          <img src="/marquee/postman.svg" alt="" />
          <img src="/marquee/angular.svg" alt="" />
          <img src="/marquee/aws.svg" alt="" />
          <img src="/marquee/figma.svg" alt="" />
          <img src="/marquee/firebase.svg" alt="" />
          <img src="/marquee/github.svg" alt="" />
          <img src="/marquee/jira.svg" alt="" />
          <img src="/marquee/postman.svg" alt="" />
          <img src="/marquee/angular.svg" alt="" />
          <img src="/marquee/aws.svg" alt="" />
          <img src="/marquee/figma.svg" alt="" />
          <img src="/marquee/firebase.svg" alt="" />
          <img src="/marquee/github.svg" alt="" />
          <img src="/marquee/jira.svg" alt="" />
          <img src="/marquee/postman.svg" alt="" />
          <img src="/marquee/angular.svg" alt="" />
          <img src="/marquee/aws.svg" alt="" />
          <img src="/marquee/figma.svg" alt="" />
          <img src="/marquee/firebase.svg" alt="" />
          <img src="/marquee/github.svg" alt="" />
          <img src="/marquee/jira.svg" alt="" />
          <img src="/marquee/postman.svg" alt="" />
          <img src="/marquee/angular.svg" alt="" />
        </div>
      </div>

      {/* Services Section */}
      <div className={styles.servicesContainer}>
        <h3 className={`${poppins.className} ${styles.serviceHeading}`}>
          How can we support you?
        </h3>

        <div className={styles.servicesContainer}>


          <ServiceCard imgSrc="/assets/img-branding.svg" title="UI/UX Design" description="Create user-friendly interfaces that enhance user experience and engagement." />
          <ServiceCard imgSrc="/assets/img-produc-design.svg" title="Web Development" description="Build responsive and dynamic websites tailored to your business needs." />
          <ServiceCard imgSrc="/assets/img-web-design.svg" title="SEO Development" description="Improve your website's visibility and ranking on search engines for better traffic." />

        </div>
      </div>

      {/* Features Section */}
      <div className={styles.featuresContainer}>
        <FeatureCard animationData={Pen} title="Unlimited Design Requests" description="Submit unlimited design requests and get all the revisions you need." />
        <FeatureCard animationData={Clock} title="Quick Turnaround" description="Enjoy fast delivery on all your projects." />
        <FeatureCard animationData={Person} title="Dedicated Designer" description="Work with a dedicated designer who understands your brand." />
        <FeatureCard animationData={Check} title="Quality Assurance" description="Our team ensures that every design meets the highest standards of quality." />
        <FeatureCard animationData={Money} title="Flexible Plans" description="Choose from a range of flexible pricing plans." />
        <FeatureCard animationData={Computer} title="Creative Solutions" description="Get unique and innovative design solutions." />
      </div>

      {/* Projects Section */}
      <div className={styles.projectParentContainer}>
        <div className={`${styles.projectHead} ${poppins.className}`}>
          <h4>Latest projects</h4>
          <p>Designing stunning products, visuals, brands, and websites: empowering startups and innovative companies to shine.</p>
        </div>
        <div className={styles.projectContainer}>
          <ProjectCard imgSrc="https://www.uiforge.design/assets/img/portfolio/img-slide-tech.webp" name="Project Name" feature="Project Feature" />
          <ProjectCard imgSrc="https://www.uiforge.design/assets/img/portfolio/img-slide-tech.webp" name="Project Name" feature="Project Feature" />
          <ProjectCard imgSrc="https://www.uiforge.design/assets/img/portfolio/img-slide-tech.webp" name="Project Name" feature="Project Feature" />
          <ProjectCard imgSrc="https://www.uiforge.design/assets/img/portfolio/img-slide-tech.webp" name="Project Name" feature="Project Feature" />
        </div>
        <div className={`${styles.bookContainer} ${poppins.className}`}>
          Book a call
        </div>
      </div>
      <section className={styles.toolsSection}>
        <div className={styles.toolsContainer} ref={ref}>
          <div class={`${styles.toolItem} ${containerIsVisible ? styles.spread1 : ''}`}>
            <img src="/tools/ic-bootstrap.svg" alt="Bootstrap logo" style={styles.toolIcon} width="16px" />
            <span>Bootstrap</span>
          </div>
          <div class={`${styles.toolItem} ${containerIsVisible ? styles.spread2 : ''}`}>
            <img src="/tools/ic-aws.svg" alt="aws logo" style={styles.toolIcon} width="16px" />
            <span>AWS</span>
          </div>
          <div class={`${styles.toolItem} ${containerIsVisible ? styles.spread3 : ''}`}>
            <img src="/tools/ic-figma.svg" alt="figma logo" style={styles.toolIcon} width="16px" />
            <span>Figma</span>
          </div>
          <div class={`${styles.toolItem} ${containerIsVisible ? styles.spread4 : ''}`}>
            <img src="/tools/ic-firebase.svg" alt="Firebase logo" style={styles.toolIcon} width="16px" />
            <span>Firebase</span>
          </div>
          <div class={`${styles.toolItem} ${containerIsVisible ? styles.spread5 : ''}`}>
            <img src="/tools/ic-git.svg" alt="Github logo" style={styles.toolIcon} width="16px" />
            <span>GitHub</span>
          </div>
          <div class={`${styles.toolItem} ${containerIsVisible ? styles.spread6 : ''}`}>
            <img src="/tools/ic-gpt.svg" alt="chatgpt logo" style={styles.toolIcon} width="16px" />
            <span>ChatGPT</span>
          </div>
          <div class={`${styles.toolItem} ${containerIsVisible ? styles.spread7 : ''}`}>
            <img src="/tools/ic-illustrator.svg" alt="Illustrator logo" style={styles.toolIcon} width="16px" />
            <span>Illustrator</span>
          </div>
          <div class={`${styles.toolItem} ${containerIsVisible ? styles.spread8 : ''}`}>
            <img src="/tools/ic-jira.svg" alt="Jira logo" style={styles.toolIcon} width="16px" />
            <span>Jira</span>
          </div>
          <div class={`${styles.toolItem} ${containerIsVisible ? styles.spread9 : ''}`}>
            <img src="/tools/ic-office.svg" alt="Office logo" style={styles.toolIcon} width="16px" />
            <span>Office</span>
          </div>
          <div class={`${styles.toolItem} ${containerIsVisible ? styles.spread10 : ''}`}>
            <img src="/tools/ic-ps.svg" alt="ps logo" style={styles.toolIcon} width="16px" />
            <span>Photoshop</span>
          </div>
          <div class={`${styles.toolItem} ${containerIsVisible ? styles.spread11 : ''}`}>
            <img src="/tools/ic-vs.svg" alt="vs code logo" style={styles.toolIcon} width="16px" />
            <span>VS Code</span>
          </div>
          <div class={`${styles.toolItem} ${containerIsVisible ? styles.spread12 : ''}`}>
            <img src="/tools/ic-xd.svg" alt="Adobe xd logo" style={styles.toolIcon} width="16px" />
            <span>Adobe XD</span>
          </div>
        </div>
      </section>


      {/* ReviewSection */}
      <section className={styles.reviewSection}>

        <div className={styles.reviewHead}>
          <h5>Words of appreciation</h5>
          <p>Discover what our clients/partners have to say about our design services.</p>
        </div>

        <div className={styles.reviewCardContainer}>
          <ReviewCard description={"Dejan is an outstanding designer who excels at quickly developing concepts and effectively incorporating feedback. His work consistently meets high standards of quality. I wholeheartedly recommend him!"} clientName={"Jeremy Smith"} clientCompany={"Founder, Seedlang"} clientImage={"https://www.uiforge.design/assets/img/template/cl-jeremy.webp"} />
          <ReviewCard description={"Dejan is an outstanding designer who excels at quickly developing concepts and effectively incorporating feedback. His work consistently meets high standards of quality. I wholeheartedly recommend him!"} clientName={"Jeremy Smith"} clientCompany={"Founder, Seedlang"} clientImage={"https://www.uiforge.design/assets/img/template/cl-jeremy.webp"} />
          <ReviewCard description={"Dejan is an outstanding designer who excels at quickly developing concepts and effectively incorporating feedback. His work consistently meets high standards of quality. I wholeheartedly recommend him!"} clientName={"Jeremy Smith"} clientCompany={"Founder, Seedlang"} clientImage={"https://www.uiforge.design/assets/img/template/cl-jeremy.webp"} />
          <ReviewCard description={"Dejan is an outstanding designer who excels at quickly developing concepts and effectively incorporating feedback. His work consistently meets high standards of quality. I wholeheartedly recommend him!"} clientName={"Jeremy Smith"} clientCompany={"Founder, Seedlang"} clientImage={"https://www.uiforge.design/assets/img/template/cl-jeremy.webp"} />
          <ReviewCard description={"Dejan is an outstanding designer who excels at quickly developing concepts and effectively incorporating feedback. His work consistently meets high standards of quality. I wholeheartedly recommend him!"} clientName={"Jeremy Smith"} clientCompany={"Founder, Seedlang"} clientImage={"https://www.uiforge.design/assets/img/template/cl-jeremy.webp"} />
          <ReviewCard description={"Dejan is an outstanding designer who excels at quickly developing concepts and effectively incorporating feedback. His work consistently meets high standards of quality. I wholeheartedly recommend him!"} clientName={"Jeremy Smith"} clientCompany={"Founder, Seedlang"} clientImage={"https://www.uiforge.design/assets/img/template/cl-jeremy.webp"} />

        </div>

        <div className={styles.reviewHead}>
          <h5>Case studies</h5>
          <p>Explore our successful projects and see the impactful results we've delivered for our clients.</p>
        </div>

        <div className={styles.projectContainer}>
          <ProjectCard imgSrc="https://www.uiforge.design/assets/img/portfolio/img-slide-tech.webp" name="Project Name" feature="Project Feature" />
          <ProjectCard imgSrc="https://www.uiforge.design/assets/img/portfolio/img-slide-tech.webp" name="Project Name" feature="Project Feature" />
        </div>

        <div className={styles.reviewHead}>
          <h5>Frequenntly asked Questions</h5>
        </div>

        <div className={styles.faqContainer}>
          <FaqCard question={"Melody Itni Chocalatey kyun hein? "} answer={"Pata nhi bhul gya"} />
          <FaqCard question={"Melody Itni Chocalatey kyun hein? "} answer={"Pata nhi bhul gya"} />
          <FaqCard question={"Melody Itni Chocalatey kyun hein? "} answer={"Pata nhi bhul gya"} />
          <FaqCard question={"Melody Itni Chocalatey kyun hein? "} answer={"Pata nhi bhul gya"} />
          <FaqCard question={"Melody Itni Chocalatey kyun hein? "} answer={"Pata nhi bhul gya"} />
        </div>

      </section>
    </div>
  );
}
